### ISSUE TITLE
Wrong color

### ISSUE THREAD

**Issue by KTibow** [einschmidt/github_dark_theme#1]
It looks like it's a light blue in your theme, when the notification dot is actually a gradient from `#54a3ff` to `#006eed`, and links have the color of `#0366d6`.

**Comment by einschmidt** [comment]
I have tried the official blue, taken from the [GitHub Color palette](https://primer.style/css/support/color-system#color-palette).

The problem is contrast, readability and therefore accessibility on the dark background. In order to gain at least AA rating I decided to use this light blue instead of the default.
